### ISSUE TITLE
problem loading a shpfile with more than 5000 layers

### ISSUE THREAD

**Issue by ehsan-sotoodeh** [calvinmetcalf/shapefile-js#102]
Hello, I have two shpfiles that are quite similar (one is simplified of the other). The first shpfile has 5000 layers and library visualize it on the map easily. second one has 10000 layers. But the library cannot load it even though the function that is called to load both files is the same. even I don't get this log. 

```
    shpfile.once("data:loaded", function() {
        console.log("finished loaded shapefile");
    });
```

Link for 5000 layers file [http://gwf-demo.usask.ca/data/shapefiles/sample-5000.zip](http://gwf-demo.usask.ca/data/shapefiles/sample-5000.zip)

link for 10000 layers file [http://gwf-demo.usask.ca/data/shapefiles/sample_10000.zip](http://gwf-demo.usask.ca/data/shapefiles/sample_10000.zip)

**Comment by ehsan99999** [comment]
Any suggestions?

**Comment by calvinmetcalf** [comment]
sorry, was on vacation, just got back, first question, are you running out of memory ?
