### ISSUE TITLE
How to use this with typescript?

### ISSUE THREAD

**Issue by YD1722** [calvinmetcalf/shapefile-js#104]
I am writing a map-based app using angular. Are there any types available for this? Or any idea how to use this in Angular?

**Comment by calvinmetcalf** [comment]
I don't use typescript so no types, you'd use this like any other js dependency

**Comment by mkaa** [comment]
is this going to work with angular 7?

**Comment by calvinmetcalf** [comment]
I don't use angular, but if angular supports modules from npm then yes it would

**Comment by hccampos** [comment]
We've managed to make this work in the latest Angular CLI by replacing `Buffer` (Angular CLI doesn't use node shims anymore):

```ts
loadShpjs(): Observable<any> {
    return new Observable<any>(observer => {
      (require as any)(
        [
          'imports-loader?BufferModule=buffer/,Buffer=>BufferModule.Buffer!../../../../../node_modules/shpjs/dist/shp.min.js',
        ],
        (shpjs: any) => {
          observer.next(shpjs);
          observer.complete();
        },
      );
    });
  }
```

**Comment by Anexo** [comment]
Hi all!

This is how I made it work on Angular 8, in case someone find it useful.

Cheers!

**Comment by lnedialkov** [comment]
This is in issue for Angular 10 where the following 2 errors occur: 
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '[object Object]'
    at Module.<anonymous> (binaryajax-fetch.js:4)

```

Replacing `module.exports =` with `export default` in binaryajax-fetch.js:4 resolves the issue.

**Comment by lnedialkov** [comment]
Made a PR for the above: https://github.com/calvinmetcalf/shapefile-js/pull/132 

@calvinmetcalf can you please review and comment if other changes might also help in this regard, thanks!

**Comment by RandomFractals** [comment]
I used it for the GeoDataViewer vscode extension to load shapefiles into keplergl. You can check out pertinent TS code bits here: https://github.com/RandomFractals/geo-data-viewer/blob/master/src/map.view.ts#L401

**Comment by calvinmetcalf** [comment]
if `import * as shapefile from 'shpjs';` doesn't work the issue is probably about how you are using typescript NOT with this module and some sort of typescrypt specific resources might end up being more helpful since I don't use ts
