### ISSUE TITLE
shpjs_1.default is not a function (angular 7)

### ISSUE THREAD

**Issue by mkaa** [calvinmetcalf/shapefile-js#107]
tried this with angular 7 but i can't find any workaround. it used to work with angular 6

**Comment by calvinmetcalf** [comment]
did something change in angular between 6 and 7 with regard to commonjs modules ? the error you get suggests it's trying to load it as a default export of a es6 module instead of a normal module.exports

**Comment by mkaa** [comment]
it worked. i'm not good with angular but i just changed

`import shp from 'shpjs';`

to

`import * as shp from 'shpjs';`
