### ISSUE TITLE
Large Files

### ISSUE THREAD

**Issue by nifhanif** [calvinmetcalf/shapefile-js#108]
Is posible to convert 10MB file or Larger?
Im try to convert 10MB zip file (around 60MB) unzip
waiting about one hours, still no result or error

**Comment by calvinmetcalf** [comment]
a 10MB zip file shouldn't take that long you are probably missing an error, this library uses promise and if you don't explicitly catch the error it can get lost, [see this article](https://hackernoon.com/promises-and-error-handling-4a11af37cb0e)

**Comment by nifhanif** [comment]
after use .catch
i got this message 
"coordinates must be finite numbers"
do you know?

note:
i also upload zip file to http://leaflet.calvinmetcalf.com/#3/32.69/10.55
and it work

**Comment by calvinmetcalf** [comment]
> "coordinates must be finite numbers"

probably an issue with the reprojecting of the data would be my guess, it is weird that it works on leaflet.calvinmetcalf considering it uses this library under the hood

**Comment by nifhanif** [comment]
Thank you...
