### ISSUE TITLE
Working around cached shapefiles

### ISSUE THREAD

**Issue by SamNelson081** [calvinmetcalf/shapefile-js#112]
I'm working with a shapefile that changes state when i call a function. However if i was to read in a shapefile polygons.shp that were to be altered via another program or function call, and to then attempt to read in the same polygons.shp after being altered, it seems as if only the cached file is retrieved, and not the new updated version. 

Is there currently a workaround to avoid this? Or could one be implemented?

**Comment by calvinmetcalf** [comment]
give it a different url should do the trick for now
