### ISSUE TITLE
Typo in shp.js

### ISSUE THREAD

**Issue by armysr** [calvinmetcalf/shapefile-js#113]
On Line 12707 of shp.js 
    var regex = /^(?:ASNI\s)?(\d+)$/m;

should be 
    var regex = /^(?:ANSI\s)?(\d+)$/m;

**Comment by pzrq** [comment]
Looks like it comes from here: https://github.com/calvinmetcalf/parseDBF/blob/master/decoder-browser.js#L9

Plus there's a PR up that may fix it: https://github.com/calvinmetcalf/parseDBF/pull/15
