### ISSUE TITLE
dist/shp.js not es5 in version 3.5.0

### ISSUE THREAD

**Issue by attekemppila** [calvinmetcalf/shapefile-js#129]
I'm using [uglify-js](https://www.npmjs.com/package/uglify-js), which is es5 only minifier. Starting from shapefile-js 3.5.0, it fails to minify shapefile-js.

Afaict, reason is non-es5 syntax (`async`) here: https://github.com/calvinmetcalf/shapefile-js/blob/11c5c104cb5e37ba665724aba70f893edb5c13a9/dist/shp.js#L37

https://github.com/calvinmetcalf/shapefile-js/blob/11c5c104cb5e37ba665724aba70f893edb5c13a9/lib/binaryajax-fetch.js#L4

Please continue to provide es5 bundle.

**Comment by hemincan** [comment]
！！！！！！！！！！！！！
