### ISSUE TITLE
Read Styled layer Descriptor ( SLD ) file in zip 

### ISSUE THREAD

**Issue by ghaithtroudi** [calvinmetcalf/shapefile-js#135]
Hello, 

I am wondering if it is possible to read an SLD xml file which can add style to the shp file

Thank you

**Comment by calvinmetcalf** [comment]
probably not? unless you know of something that will translate an SLD file into [simple style](https://github.com/mapbox/simplestyle-spec)

**Comment by ghaithtroudi** [comment]
Hello, 
i made a small dictionary like this one to bind leaflet properties to SLD's SvgParameter
`  const dictionarySldToLeaflet = {
	color: {
		sldName: 'color',
		defaultName: 'color'
	},
	stroke: {
		sldName: 'stroke',
		defaultName: 'stroke',
	},
	weight: {
		sldName: 'stroke-width',
		defaultName: 'stroke-width',
	},
	opacity: {
		sldName: 'opacity',
		defaultName: 'opacity',
	},
	lineJoin: {
		sldName: 'stroke-linejoin',
		defaultName: 'stroke-linejoin',
	},
	fill: {
		sldName: 'fill',
		defaultName: 'fill',
	}
  };`

There is also a filter that i can parse to determine which features are styled in the shp file here is an example : 
`            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>{PROPERTY}</ogc:PropertyName>
              <ogc:Literal>{VALUE}</ogc:Literal>
            </ogc:PropertyIsEqualTo>`

Do you think that it's possible to add a style property to features if i manage to create an object like this one ?
`
foo = { filters: [ { property: value }] , styles : { fill: ... , color: ..... , weight: .....} } 
`

Thank you

**Comment by ghaithtroudi** [comment]
After having a little search, i found this repo 
https://github.com/orfon/Leaflet.SLD

Is it possible to use leaflet.sld.js to style the shp file ? 

I ama asking these question since i'm not familiar with shp / sld files 

Thank you

**Comment by calvinmetcalf** [comment]
so if you are loading the shapefile from a remote url, you could just load the sld file yourself, if it's a zip file then you wouldn't have access to that I suppose I could try to come up with a way to get the other files out of the zip to you, maybe events ?

**Comment by ghaithtroudi** [comment]
Here is what i did : 

- I parsed the sld file and got some style properties and filters ( some, not all ) 
- I filtered the features array in the object that i get from shpjs and added a "style" property to each feature depending on the filter in the SLD file 
- i used the GeoJson method "style" to apply feature.style to each feature and it seemed to work

My idea is to style automatically reading the SLD from the zip too.

PS : i saw that it is not possible to read the shp file without the dbf, is there a way to only read the shp ? 

Thank you

**Comment by calvinmetcalf** [comment]
> PS : i saw that it is not possible to read the shp file without the dbf, is there a way to only read the shp ?

pass the buffer containing the shp file to `shp.parseShp`
