### ISSUE TITLE
Can't convert from EPSG:31467

### ISSUE THREAD

**Issue by isthisstackoverflow** [calvinmetcalf/shapefile-js#140]
Hi there,

I'm getting an error trying to use [this file](https://filebin.net/ozk85sxcjf4w6x8x/Polygon_31467.zip?t=kj2stza2) on [the example page](http://leaflet.calvinmetcalf.com/). (Actually I'm writing my own client, but it's probably the same issue on the example page - at least the error looks samey.)

Importing from EPSG:25832 works just fine. and I can load the uploaded file into QGIS without warnings/errors. So maybe this is an issue with the library? Or maybe I'm doing something wrong.

```js
// This has been added to proj4.defs, which afaik this package, too, uses
[
      'EPSG:31467',
      '+title=Bessel/Gauß-Krüger 3 +proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel +datum=potsdam +units=m +no_defs',
]
```

```js
// This is the error appearing, but I'm not sure what it's telling me
PROJCS["DHDN_3_Degree_Gauss_Zone_3",GEOGCS["GCS_Deutsches_Hauptdreiecksnetz",DATUM["D_Deutsches_Hauptdreiecksnetz",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Gauss_Kruger"],PARAMETER["False_Easting",3500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",9.0],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]
```

Any help appreciated!

**Comment by calvinmetcalf** [comment]
so this package doesn't mess around with `proj4.deffs` and just loads the .prj file that comes with the shpaefile, so I'm not totallys ure what you are trying to do...

**Comment by isthisstackoverflow** [comment]
Oh, nevermind that part of my post then.

What's left is that I'm trying to upload [this file](https://filebin.net/ozk85sxcjf4w6x8x/Polygon_31467.zip?t=kj2stza2) with the package, which doesn't work, as can be seen on [the example page](http://leaflet.calvinmetcalf.com/#3/32.69/10.55).

**Comment by isthisstackoverflow** [comment]
My other upload timed out, so I re-uploaded the file here: https://gofile.io/d/RuwHAB

Seems like the library simply can't handle EPSG:31467; something in reading the .prj file breaks, which is why the example page (http://leaflet.calvinmetcalf.com/#3/32.69/10.55) prints the file's contents as error message.

I tried digging in the source code, but it seems I am not quite skilled enough to get what's going on in there.

**Comment by isthisstackoverflow** [comment]
After some more searching I found an issue proj4js/proj4js#143 that indicates proj4 simply does not support what I'm trying to upload.
