### ISSUE TITLE
Can't load index.html

### ISSUE THREAD

**Issue by anonymouskeyboard47** [calvinmetcalf/shapefile-js#144]
Hi,

I downloaded the entire project and ran the index.html file but nothing displayed, except that the Leaflet control with its minimize and maximize buttons were shown. The attributions were also shown.

Is there something else I should download for it to work?

Regards

**Comment by calvinmetcalf** [comment]
depends what the exact error is you're seeing in the console, you probably need to run a local server to see it, if you are using node.js you could use serve by running `npx serve`
