### ISSUE TITLE
unable to load locally saved shape file

### ISSUE THREAD

**Issue by KanupriyaGoel** [calvinmetcalf/shapefile-js#146]
Hi,

I am trying to give path for a file on my system to be read and loaded onto the map but I get error that path should contain Http or Https. As per documentation I think this can be done, is this not correct?

Thanks,
Kanupriya

**Comment by calvinmetcalf** [comment]
You need to load it from a web url not one that starts with file:// try
running a small web server via something like npx serve

**Comment by KanupriyaGoel** [comment]
Hey,

Thanks, I will try it. But I tried to pass in an ArrayBuffer and even that
didn't work.
