### ISSUE TITLE
Unable to use with Webpack 5

### ISSUE THREAD

**Issue by 3zzy** [calvinmetcalf/shapefile-js#148]
Webpack 5 doesn't include node polyfills anymore so I'm having issues using the library. 

`Error: nodebuffer is not supported by this browser` 

![error](https://i.imgur.com/afepBBQ.png)

I already tried this in my Webpack config:

```
resolve: {
    fallback: {
        fs: false,
        path: require.resolve("path-browserify"),
        buffer: require.resolve("buffer")
    }
}
```

and even setting these to `false` but no luck.

**Comment by 3zzy** [comment]
So I installed the [node-polyfill-webpack-plugin](https://github.com/Richienb/node-polyfill-webpack-plugin#readme) and now there's a different error:

`TypeError: r.isBuffer is not a function`

![error](https://i.imgur.com/swiBuwY.png)

**Comment by calvinmetcalf** [comment]
any chance you can show non minified stack trace ?

**Comment by 3zzy** [comment]
@calvinmetcalf Sure

<img width="772" alt="Screen Shot 2020-12-24 at 11 56 14 am" src="https://user-images.githubusercontent.com/105034/103047277-0b078d80-45df-11eb-818a-fc61c3de986d.png">

![error](https://i.imgur.com/oswyJXx.png)

**Comment by calvinmetcalf** [comment]
[this comment](https://github.com/webpack/changelog-v5/issues/10#issuecomment-615877593) suggests you may have to do

```js
new webpack.ProvidePlugin({
  Buffer: ['buffer', 'Buffer'],
})
```
