### ISSUE TITLE
What was it that changed?

### ISSUE THREAD

**Issue by aafenlared** [calvinmetcalf/shapefile-js#149]
Thanks for this library.  I have been trying to found this answer, but the code have changed a lot.
With the version of "shp.js" used in the example "Local Zipfile" the accents are displayed correctly without using a cpg file. Meanwhile, using the newer version of "shp.js" are not displayed correctly unless the cpg file is included? My shapefile is encoded ISO-8859-1. Sorry my english. I hope you understand.

**Comment by calvinmetcalf** [comment]
we should be defaulting to utf8 or ascii if the cpg is omitted which is what you are passing so I'm not totally sure what the problem could be

**Comment by calvinmetcalf** [comment]
https://github.com/calvinmetcalf/parseDBF is where stuff might have been changed
