### ISSUE TITLE
Grid Based Datum Adjustments

### ISSUE THREAD

**Issue by pseudonem** [calvinmetcalf/shapefile-js#151]
Is there a way to supply grid based datum adjustments, as per this [link](https://github.com/proj4js/proj4js#grid-based-datum-adjustments), to the proj4 function call in this library?

I'd like to use the library with NAD83 shapefiles at a higher accuracy than the default proj4 projection.

**Comment by calvinmetcalf** [comment]
there is not, you can omit the .prj file and then manually reproject the files your self after they are parsed
