### ISSUE TITLE
Error: nodebuffer is not supported by this browser

### ISSUE THREAD

**Issue by Mylothros-Charalampos** [calvinmetcalf/shapefile-js#166]
I am uploading .zip file which has shapefile in it, I am converting it into a buffer and the moment I pass the buffer in shp(buffer) I get this error Error: nodebuffer is not supported by this browser. I am using gatsby v3 with react and react dom 17.0.1 respectively. I tried already only to apply the .shp file and use shp.parseShp('.shpfile') and it works but I dont get to pass any feature.properties like this. Do you have any suggestion why this could happen.

**Comment by calvinmetcalf** [comment]
use this in your webpack config (that's what gatsby uses under the hood) https://github.com/Richienb/node-polyfill-webpack-plugin)

**Comment by Mylothros-Charalampos** [comment]
thank you it worked :)

**Comment by weixiaoxiang** [comment]
thank you it worked :)
