### ISSUE TITLE
Doesn't work with file coming from an input file?

### ISSUE THREAD

**Issue by diegottivos** [calvinmetcalf/shapefile-js#172]
I'm calling an onChange but it gives me an error

```html
<input accept=".zip" onChange={importShape} type="file" />
```

```javascript

const importShape = async (data) => {
    const file = data.target.files[0];

    const geojson = await shp(file);

    console.log(geojson);
  };

```

![image](https://user-images.githubusercontent.com/92583434/143321994-0951fcb7-e6f8-4126-a7f9-2ff6fcbc8bde.png)

**Comment by kuztom** [comment]
Hi!
Did you come up with a solution? Im having same problem..
Additional details on how this was accomplished would be appreciated.
