### ISSUE TITLE
Library ceased to work in client-side applications

### ISSUE THREAD

**Issue by Christoph142** [calvinmetcalf/shapefile-js#210]
Hi there,
We have been using version 4 in angular in the browser.
Updating to version 5 results in an error about "nodebuffer" not being available.
Anything that can be done about this?

**Comment by calvinmetcalf** [comment]
new version 5.1.0 is going to remove all instances of nodebuffer, hang tight

**Comment by Christoph142** [comment]
Thanks for the update. Really appreciated! ✌️

**Comment by calvinmetcalf** [comment]
ok it's actually version 6.0.1 and it's out now

**Comment by Christoph142** [comment]
Updated from 4.0.2 to 6.0.1 now. Seems to work flawlessly (had to change the import from dist package to root). Thanks @calvinmetcalf ! 🍻
