### ISSUE TITLE
Imported shapefile results in invalid generated geojson

### ISSUE THREAD

**Issue by msereda** [calvinmetcalf/shapefile-js#221]
Hi - A shapefile I have attached gets imported but 2 of the 3 items have invalid geojson that then can't be used in a map.

The same file imports successfully into the online mapshaper tool and results in valid geojson when exported.

[20241122_102517_SHP.zip](https://github.com/user-attachments/files/17877050/20241122_102517_SHP.zip)

**Comment by calvinmetcalf** [comment]
you've got...invalid geometries, the middle and right hand shapes have ring self intersections 
<img width="308" alt="Screenshot 2024-11-25 at 10 33 15 AM" src="https://github.com/user-attachments/assets/c8404aa7-aa26-41bf-b7b8-e147daaf04a8">
<img width="381" alt="Screenshot 2024-11-25 at 10 32 53 AM" src="https://github.com/user-attachments/assets/9dc7ca5d-855c-439f-b4d8-e2b835a8a3ec">

this library doesn't judge you and simply gives you the the geojson version of what you put in, mapshaper might be doing some clean up

**Comment by msereda** [comment]
Thanks for the reply Calvin, I didn't have access to a local shapefile viewer so I was unable to see those issues - the original shapefile came from 3rd party software.
