### ISSUE TITLE
parseShp/parseDbf not a method

### ISSUE THREAD

**Issue by u-jo** [calvinmetcalf/shapefile-js#34]
When trying to use combine, the shp.parseShp and parseDbf are not available methods

**Comment by cc-erty** [comment]
I'm experiencing a similar issue, in index.js:109, I believe there should be a call to `shp.parseDbf` instead of just `parseDbf`.

**Comment by calvinmetcalf** [comment]
[it's definitely exported](https://github.com/calvinmetcalf/shapefile-js/blob/12b2995e6dc7d7e728113e7f6613c421fbeab565/lib/index.js#L133) and the internal method it hits the [right method](https://github.com/calvinmetcalf/shapefile-js/blob/12b2995e6dc7d7e728113e7f6613c421fbeab565/lib/index.js#L7)
