### ISSUE TITLE
rawinflate.min.js.map 404 (Not Found)

### ISSUE THREAD

**Issue by MappingKat** [calvinmetcalf/shapefile-js#39]
This only happens when I use to beautified code (shp.js) and not the minified version (shp.min.js), I get a 404 error on rawinflate.min.js.map.  Do I need to include this?  How do I correct this?

Is it related to this issue?  https://github.com/Stuk/jszip/issues/75

Thanks for making this library!

**Comment by calvinmetcalf** [comment]
yes they are the same issue, since it sounds like it was fixed upstream you can rebuild the library and it should go away).

**Comment by denny123** [comment]
I have some problem, what i must doing?

**Comment by denny123** [comment]
Bad comment in shp.js, needed:

    /*//@ sourceMappingURL=rawinflate.min.js.map*/

and

    /*//@ sourceMappingURL=rawdeflate.min.js.map*/
