### ISSUE TITLE
Adding multiple shapes with ArrayBuffers always returns the first shape from cache

### ISSUE THREAD

**Issue by davidlukerice** [calvinmetcalf/shapefile-js#40]
The `hasOwnProperty` check for cache hits uses the passed in object's `toString` method. So it always returns `"[object ArrayBuffer]"` as the cache key when using `ArrayBuffers`. When you try to load multiple `ArrayBuffer` shapes, it thinks they are all the same as the first (matching `toString`), so it just returns the first shape layer.

This can be solved by overriding the `toString` method each time with something like
``` javascript
var req = new XMLHttpRequest();
req.open('GET', urlToZipFile);
req.responseType = 'arraybuffer';
req.onload = function(event) {
    if (req.response) {
        req.response.toString = function() {
            return urlToZipFile;
        };
        var shapeLayer = L.shapefile(req.response);
        scope.addShapeToMap(shapeLayer);
    }
};
req.send(null);
```

but would prefer `shapefile-js` to use a hash or optional value as an object's key. If there is a preferred way, I can probably put in a PR with the change.
Like changing https://github.com/calvinmetcalf/shapefile-js/blob/0d74c45a1927ea824bad48dd08c300c5b9bba0b3/lib/index.js#L13 to
``` javascript
function shp(base, whiteList) {
  var hash = typeof base === 'string' ? base : SparkMD5.ArrayBuffer.hash(base);
	if (cache.has(hash)) {
		return Promise.resolve(cache.get(hash));
	}
	return shp.getShapefile(base, whiteList).then(function (resp) {
		cache.set(hash, resp);
		return resp;
	});
}
```

**Comment by calvinmetcalf** [comment]
fixed in 3.2.0
