### ISSUE TITLE
lru cache should be optional

### ISSUE THREAD

**Issue by nmccready** [calvinmetcalf/shapefile-js#41]
Cool library! Using this in node it is probably not ideal (memory could be huge even at just 20 items) to be using the LRU cache for long running applications. It would be nice if this was optional where it can be turned off entirely and or change the allowed cache size.

**Comment by calvinmetcalf** [comment]
this is mainly for use in the browser, I have a fork of @mbostock's shapefile parser (that I have an open pull to merge back in mbostock/shapefile#18) which is what I recommend for the server as it supports real streams i.e. arbitrarily large streams from networks, that being said I have no memory of why I put the lru cache in and may need to look back into that

**Comment by nmccready** [comment]
One downside to mbostock/shapfile is that it doesnt seem to support zip files like this.

**Comment by nmccready** [comment]
Another good option, https://github.com/substack/shp2json as I was thinking of using the unzip binary.

**Comment by calvinmetcalf** [comment]
yeah there are a couple of options for streaming unzip if you don't
mind writing them to disc
