### ISSUE TITLE
File API support?

### ISSUE THREAD

**Issue by paranoicsan** [calvinmetcalf/shapefile-js#42]
Hi!

Any plans to allow parse shp-files uploaded via File API?

Thanks!

**Comment by calvinmetcalf** [comment]
you can use fileReader.readAsArrayBuffer to get the file as an arrayBuffer which you can just pass in here

**Comment by paranoicsan** [comment]
Thanks for reply!

I try to load SHP via following block but get `Error: Corrupted zip : can't find end of central directory`. Any advise?

```javascript
var reader = new FileReader();
reader.onload = function() {
    shp(this.result).then(function(geoJSON) {
        console.debug(geoJSON);
    }, function(e) {
        console.debug(e);
    });
};
reader.readAsArrayBuffer(files[0]);
```

**Comment by calvinmetcalf** [comment]
double check that it is a valid zipfile from the command line?

**Comment by paranoicsan** [comment]
Hm. It was not zip-file - just simple shp-file. 

Is it possible to convert just shp-data without other parts (dbf and others)?

**Comment by calvinmetcalf** [comment]
shp.parseShp

**Comment by paranoicsan** [comment]
I got it. Thanks!
