### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by michaelvaneck** [calvinmetcalf/shapefile-js#48]
So is there any way how to use this with local files? I'm using AngularJS with File API to upload my files. I'd rather process it locally then upload it to my server, return the path and then process it.

or maybe use dataUrl?

**Comment by calvinmetcalf** [comment]
yes you can pass it an array buffer

**Comment by michaelvaneck** [comment]
I continued working on it but even when giving it an ArrayBuffer it somehow doesn't work?

    function readFile(file) {
            $log.info('mapcontroller: reading File...');
            $log.info('mapcontroller: Filetype: ' + file.type);
            $log.info(file);

            var reader = new FileReader();
            var byteArray = undefined;

            reader.onload = function (e) {
                byteArray = e.target.result;
                $log.info('mapcontroller: creating ArrayBuffer');
                $log.info(byteArray);
            }
            reader.onerror = function (event) {
                console.error("File could not be read! Code " + event.target.error.code);
            };

            //reader.readAsText(file);
            reader.readAsArrayBuffer(file);

            shp(byteArray).then(function (floep) {
                $log.info(floep);
            });

        }

**Comment by calvinmetcalf** [comment]
Add a .catch(onErrFn) to the end of the promise chain (after the .then())
to see any errors that are thrown.

**Comment by michaelvaneck** [comment]
Got it working, thx for the fast responses!!

**Comment by Shraddhaz** [comment]
@michaelvaneck @calvinmetcalf  What is the fix for this ? I am having the same issue. I want to convert the shp file read by arraybuffer to geojson. The .zip works fine, but not the .shp. Any idea ?

**Comment by calvinmetcalf** [comment]
by default you can only do .zip locally and .shp from remote urls

**Comment by Shraddhaz** [comment]
Is there no way to do .shp locally using shapefile-js ?

**Comment by calvinmetcalf** [comment]
yeah you need to call `shp.combine([shp.parseShp(shpArrayBuffer, projString), shp.parseDbf(dbfArrayBuffer)])`

so to break that down, shp.parseShp takes an array buffer corresponding to the  .shp file and an optional string corisponding to the .prj file, then shp.parseDbf take an array buffer corresponding to the .dbf file and the shp.combine takes an array of the results of those 2 functions.
