### ISSUE TITLE
List of supported projections

### ISSUE THREAD

**Issue by jczaplew** [calvinmetcalf/shapefile-js#50]
Is there a list of supported projections anywhere? Thanks!

**Comment by calvinmetcalf** [comment]
Anything proj4js supports which includes state plane and utm and a LOT of
other stuff, though some of the more obscure stuff may have some untested
edge case bugs.

**Comment by jczaplew** [comment]
I noticed that if an unsupported projection is passed, it is returned as the error in `.catch`. Is there a good way to determine if the parse failed because of an unsupported projection or some other reason?

**Comment by calvinmetcalf** [comment]
If there is an invalid projection file (or one proj4js, which is probably
more likely issue than a projection that isn't supported) you will get an
error from proj4js while if you get an error from something else you will
get one from this library (or some other non proj4js library) so looking at
the stack trace would be one way to know

**Comment by jczaplew** [comment]
Cool, thanks for the help!
