### ISSUE TITLE
Local Zipfile example in IE 10

### ISSUE THREAD

**Issue by gabalmat-csg** [calvinmetcalf/shapefile-js#53]
It doesn't look like the local zipfile example works in IE 10.  I tried both dragging and dropping a file as well as uploading it.  I'm asking about this because I allow the user to drag a drop a zipfile containing a shapefile in my application.  I am using this library to get the geojson.  It works fine in IE 11, but in IE 10 it looks like the promise is never resolved.

I was hoping you could provide some insight.  Thanks.

**Comment by gabalmat-csg** [comment]
I should have been more clear about which promise isn't resolving -- the promise that is returned from the shp function.  Thanks.

**Comment by calvinmetcalf** [comment]
do you get any errors in dev tools (hit f12 to open them)

**Comment by gabalmat-csg** [comment]
I don't get any errors in my application, and when I run your example in IE 10, I get the spinning wheel that spins indefinitely, without any error as well.  thanks so much

**Comment by calvinmetcalf** [comment]
neither on the console or the network tab?

**Comment by gabalmat-csg** [comment]
right, I don't see any errors in either tab

**Comment by calvinmetcalf** [comment]
do you have a .catch handler on the promise ?

**Comment by gabalmat-csg** [comment]
Ok, I just added a catch handler but it doesn't seem to be going into that either as nothing was logged to the console.  This is how I used it:

importShp: function(data, callback) {
            shp(data).then(function(geojson) {
                callback(geojson);
            }).catch(function (reason) {
                console.log(reason);
            });
        }

**Comment by gabalmat-csg** [comment]
I think I found the culprit. In my application, I wrap the shp() method in a webworker (operative.js) and I notice that you are doing the same in your local zipfile example using catiline.js.  I took the method out of the webworker in my application and it is working fine. operative.js supports IE10 with non-blob worker support so I'm not exactly sure why that is causing the problem. I'll probably just do an IE version check, unless you or anyone else has a better idea.  Thanks for your help.

**Comment by gabalmat-csg** [comment]
EDIT: According to: 
https://github.com/padolsey/operative/issues/36 
it looks like the webworker must be instantiated like so for IE 10 support:
new Worker('the/path/to/operative.js');

this fixed my problem so I'll go ahead and close the issue. Thanks
