### ISSUE TITLE
Error using shapefiles in EPSG:3995

### ISSUE THREAD

**Issue by aaronpmishkin** [calvinmetcalf/shapefile-js#54]
I get the error below when I attempt to convert a shapefile in EPSG:3995 to geojson. The shapefile contains a single polygon and was created using QGIS Pisa.

RangeError: Invalid typed array length
    at new Uint8Array (native)
    at dbfRowHeader (http://localhost:8080/common/lib/shp/dist/shp.js:11964:43)
    at module.exports (http://localhost:8080/common/lib/shp/dist/shp.js:12011:19)
    at Function.shp.parseZip (http://localhost:8080/common/lib/shp/dist/shp.js:17562:58)
    at http://localhost:8080/common/lib/shp/dist/shp.js:17622:16
    at tryToUnwrap (http://localhost:8080/common/lib/shp/dist/shp.js:11491:5)
    at tryCatch (http://localhost:8080/common/lib/shp/dist/shp.js:11515:17)
    at Object.safelyResolveThenable [as safely] (http://localhost:8080/common/lib/shp/dist/shp.js:11494:16)
    at new Promise (http://localhost:8080/common/lib/shp/dist/shp.js:11326:21)
    at Function.shp.getShapefile (http://localhost:8080/common/lib/shp/dist/shp.js:17621:10)

**Comment by aaronpmishkin** [comment]
I have resolved the above issue. It seems that the shapefiles were being corrupted during creation. However, I have run into two issues with converting my shapefiles.

1: EPSG:3031 is not a supported projection, but I believe that you mentioned somewhere that all projections in proj4js should be supported. I took a look at the code, and EPSG:4326 has a projection name of "Stereographic_South_Pole", which is not in the list of projection names you use to look up the projection. However, "Stereographic_North_Pole" is in the list, as is "polar_stereographic". Both "polar_stereographic", and "Stereographic_North_Pole" refer to the same projection. Is "Stereographic_South_Pole" also supposed to fall under this projection?

2: I am experiencing significant distortion of my EPSG:3995 shape files during conversion into geojson. It is very strange. It occurs both on my application and your demo at: http://leaflet.calvinmetcalf.com/#3/32.69/10.55. Any idea as to why this would be happening?

**Comment by calvinmetcalf** [comment]
1. looking at http://epsg.io/3031 it would seem they are all the same thing so Stereographic_South_Pole needs to be put in as an alias for polar_stereographic.
2. assuming that the reason you are using Stereographic_South_Pole as a projection is because your data is of a location in Antarctica, then the distortion is likely due to the mercator projection which causes massive distortions in the pools and is really only good up to +-85 latitude

**Comment by aaronpmishkin** [comment]
1. Great! I'll do that.
2. I'm creating the data in Stereographic_Pole_Pole and then displaying in that same projection. How would the mercator projection be causing the distortion? Additionally, the location of the data is affected as well as the geometry.

**Comment by calvinmetcalf** [comment]
Can you post a screen shot of the distortion?

**Comment by aaronpmishkin** [comment]
![capture](https://cloud.githubusercontent.com/assets/9100927/11383094/ba551f06-92ba-11e5-8f61-c99639d2b9f2.JPG)

The more northerly polygon is the undistorted one that I directly output as geojson. The other polygon is from the same data, but was saved as a shapefile and then converted into geojson.

**Comment by calvinmetcalf** [comment]
Is the southern shift also part of the problem or is that for
demonstration?

**Comment by aaronpmishkin** [comment]
It's also part of the problem.

**Comment by calvinmetcalf** [comment]
hm can you post the shapefile so I can take a look at it?

**Comment by calvinmetcalf** [comment]
actually [stereographic_south_pole is a projection  available in proj4](https://github.com/proj4js/proj4js/blob/954d465d68e29511661cb52c308311c8729cfed3/lib/projections/stere.js#L166)

**Comment by aaronpmishkin** [comment]
https://drive.google.com/file/d/0B-M6FEcA3sgKRlVtQWJ3dTZKUmc/view?usp=sharing

Google Drive link to the zip file. Sorry for the delay in getting this to you.

Also, it seems that the conversion projects the shapefile into EPSG:4326. However, it was my intent to preserve the original projection and then do the transformation myself. Is this possible?

**Comment by calvinmetcalf** [comment]
Yes shapefile-js projects to wgs84, I can take a closer look at this on
Monday

**Comment by aaronpmishkin** [comment]
Any progress on this?

**Comment by calvinmetcalf** [comment]
this is a problem with proj4js so you're better off opening an issue there (https://github.com/proj4js/proj4js)
