### ISSUE TITLE
Poor performance compared to examples

### ISSUE THREAD

**Issue by TehNrd** [calvinmetcalf/shapefile-js#56]
This library is working great, but I am seeing performance that is much slower than what I see in the examples, using the exact same Shape File.

Here is a simple shape file of Los Angeles county postal codes:
[LA_Postal_Codes.zip](https://github.com/calvinmetcalf/shapefile-js/files/123388/LA_Postal_Codes.zip)

When I drag and drop the file on this sample page, http://leaflet.calvinmetcalf.com/#9/33.7540/-117.8174 , the results are added to the map in less than a second!

I created a very simple page to read this Shape File and it is consistently taking nearly 4 seconds to read the shape file. I can't seem to understand why there is such a discrepancy. I am using web workers, fwiw.

Here is fully functional plunkr with the simplest code I could come up with to reproduce these performance issues. http://plnkr.co/edit/JuEAGpzViRKym7Wh7rL6?p=preview

And here is the page source, but it would require some tweaks to point to script files to the correct locations.

```html
<!DOCTYPE HTML>
<html>
	<head>
		<script type="text/javascript" src="./js/lib/shp.js"></script>
		<script type="text/javascript" src="./js/lib/catiline.js"></script>

		<style>
			body{
				margin: 0px;
				padding: 0px;
			}
			#fileDropDiv{
				width: 400px;
				height: 200px;
				background-color: #6BCC8A;
			}
		</style>
	</head>
	<body>
		<div id="fileDropDiv">
			Drag and Drop Zipped Shape File here!
		</div> 

		<script type="text/javascript">

			var worker = cw(function(data){
			    importScripts('./js/lib/shp.js');
			    return shp.parseZip(data);
			});

			//Setup the FileReader
			var reader = new FileReader();

			reader.onload = function(event) {

				var bufferArray = event.target.result;

				console.time('shp');
				worker.data(bufferArray).then(function(data){
				    console.timeEnd('shp');
				});
			};

			//Setup the drop div
			var fileDropDiv = document.getElementById('fileDropDiv');
			fileDropDiv.ondragover = function(){ return false; };
			fileDropDiv.ondragend = function(){ return false; };
			fileDropDiv.ondrop = function(e){

				e.preventDefault();

				//Only handle a single file for demo
				var files = e.dataTransfer.files;
				var file = files[0];

				//Read the shape file
				reader.readAsArrayBuffer(file);

				return false;
			};
		</script>

	</body>
</html>
```

**Comment by calvinmetcalf** [comment]
judging by the flame graphs 

leaflet.calvinmetcalf.com: 
![screen shot 2016-02-09 at 12 55 20 pm](https://cloud.githubusercontent.com/assets/1128607/12925473/7998810c-cf2c-11e5-964e-0078a61ddfdb.png)

your plunker:

<img width="1100" alt="screen shot 2016-02-09 at 12 55 38 pm" src="https://cloud.githubusercontent.com/assets/1128607/12925483/828f430e-cf2c-11e5-889a-7f8fe65b0aba.png">

the issue is with the version of jszip that is bundled with it

**Comment by TehNrd** [comment]
Thanks, yup, I hard started to isolate it to the same area.
<img width="1201" alt="screen shot 2016-02-09 at 1 21 58 pm" src="https://cloud.githubusercontent.com/assets/1007085/12927948/ebb77b92-cf38-11e5-830a-d365a5bc91ba.png">


Looks like dist/shp.js and dist/shp.min.js are out of out of date, need to be rebuilt, and committed to master. To fix all I did was pull down master, run the build script, and then performance was much improved. Same file is now read is 200ms.

**Comment by TehNrd** [comment]
Submitted #57 which should fix this.
