### ISSUE TITLE
Local shapefile issue

### ISSUE THREAD

**Issue by jaysmith1987** [calvinmetcalf/shapefile-js#59]
When using the code for the local shapefile it only allows me to upload one shapefile and that is it.

**Comment by calvinmetcalf** [comment]
what code for local shapefile ?

**Comment by jaysmith1987** [comment]
in your leaflet.calvinmetcalf.com page it allows the user to upload a shapefile in zip format to your map.  The issue is it only allows the user to upload one shapefile.  Do you know hot to make it so the user can add more than one shapefile?

**Comment by calvinmetcalf** [comment]
ah I see, there is a bug that causes the first one to be re added instead
of adding a new one

**Comment by calvinmetcalf** [comment]
should be fixed

**Comment by jaysmith1987** [comment]
can you reference how you fixed it.  I am working on a program were I have to use that fix

**Comment by calvinmetcalf** [comment]
https://github.com/calvinmetcalf/leaflet.workspace/commit/09f1025825e0d76036e9d524e481b09b6c7398db

I basically just manually put in a fix that we had in this repo already for dealing with blobs
