### ISSUE TITLE
file extension uppercase

### ISSUE THREAD

**Issue by joaosr** [calvinmetcalf/shapefile-js#64]
When use a file with name name.DBF or name.PRJ or name.SHP, parseShp doesn't work. why this happen?

**Comment by calvinmetcalf** [comment]
because javascript is case sensitive so .DBF is not the same as .dbf

**Comment by joaosr** [comment]
I did one change on `shp.js` file, I added in this code:

`parsed = shp.combine([parseShp(zip[name + '.shp'], zip[name + '.prj']), zip[name + '.dbf']]);`
`parsed.fileName = name;`

more this:

`var _shp = zip[name + '.shp'] || zip[name + '.SHP'];`
` var _prj = zip[name + '.prj'] || zip[name + '.PRJ'];`
`var _dbf = zip[name + '.dbf'] || zip[name + '.DBF'];`

 `parsed = shp.combine([parseShp(_shp, _prj), _dbf]);`
`parsed.fileName = name;`

Now I can import file with uppercase extension.

**Comment by calvinmetcalf** [comment]
we probably would need a more general solution that can deal with mixed case files as well e.g. `.dbF`

**Comment by joaosr** [comment]
In my case the pattern .SHP is very common in Brazil. I am going work in a solution for that, i wish get some  headway.

**Comment by calvinmetcalf** [comment]
i looked into fixing this and remembered [this code](https://github.com/calvinmetcalf/shapefile-js/blob/12b2995e6dc7d7e728113e7f6613c421fbeab565/lib/index.js#L49-L61) which is supposed to deal with just your problem, are you purchance using an older version ?
