### ISSUE TITLE
Marker on geojsonlayer (shapefile)

### ISSUE THREAD

**Issue by shashi19dongare** [calvinmetcalf/shapefile-js#67]
hi,
     I am loading map using L.geojson layer (shapefile) its working fine . but now i want to display markers on geojson layer for example circle,rectangle,icons etc. Pointtolayer event is not getting called because in feature object  geometry type is polygon as shown in image3. so i used oneachfeature event to load markers. markers are getting loaded but they are getting displayed at background of layer see image 1. on mouseover marker it gets displayed blur at background of layer(image2) .I want to show marker,icons at front.code used to display marker in oneachfeature is shown in image4. 
[New folder.zip](https://github.com/calvinmetcalf/shapefile-js/files/380799/New.folder.zip)

**Comment by calvinmetcalf** [comment]
so this just turns the shapefile into a geojson layer, you probably want to get help at the main [leaflet repo](https://github.com/Leaflet/Leaflet), also you can posh images directly to an issue without having to zip them
