### ISSUE TITLE
Error parsing shapefile

### ISSUE THREAD

**Issue by knittingjidda** [calvinmetcalf/shapefile-js#71]
When parsing the shapefile, occasionally the shapetype comes back as 1634038337. This is on a polyline shapefile. If I divide the shapefile into smaller section of about 100 features, it will work or work after several tries. It doesn't seem to be consistent. I have several other shapefiles where it works perfectly every time with several thousand features, so I don't think the feature count is actually the issue.

In addition, I have run into an issue where I may need to try once or twice to get the file read properly.

**Comment by calvinmetcalf** [comment]
can you post the file in question anywhere?
