### ISSUE TITLE
Can't read shapefiles zipped up on mac.

### ISSUE THREAD

**Issue by chriserickson** [calvinmetcalf/shapefile-js#73]
Hello,
When trying to open the attached shapefile, or any that was zipped up on a Mac, I get an error:

[Archive.zip](https://github.com/calvinmetcalf/shapefile-js/files/811440/Archive.zip)
"Offset is outside the bounds of the DataView" (chrome)

It appears to be coming from code reading a dbf row header, but the error went away if i unzip/rezip on Windows, and has happened for multiple shape files.

**Comment by calvinmetcalf** [comment]
weird, I'm on a mac too

**Comment by chriserickson** [comment]
Were you able to reproduce it? It originally came up with an end-user of our product having the issue, and I was able to reproduce with my personal mac. I took a perfectly good shape file, unzipped it and re-zipped it on the mac, and ran into the error.

**Comment by calvinmetcalf** [comment]
probably won't get around to digging in until tommorow

**Comment by calvinmetcalf** [comment]
how are you trying to open it, it works on http://leaflet.calvinmetcalf.com/#10/37.7061/-104.7670

**Comment by chriserickson** [comment]
I'm getting a lot of 401 errors for the mapbox api on that page, and the drag and drop is doing nothing....

**Comment by calvinmetcalf** [comment]
Yeah switch the layer picker in the top right and then zoom into your layer
which is there

**Comment by chriserickson** [comment]
The problem went away when I updated to the newest version of shp.js...
