### ISSUE TITLE
Shapefile crossing the antimeridian converted incorrectly 

### ISSUE THREAD

**Issue by audreyhession** [calvinmetcalf/shapefile-js#79]
I have a shapefile containing a polygon that crosses the antimeridian.  Shapefiles determine the interior of a polygon by the order of vertices, specifically, the exterior ring vertices are in clockwise order. (http://www.esri.com/library/whitepapers/pdfs/shapefile.pdf page 8) GeoJSON doesn't follow any particular vertex ordering, thus to indicate antimeridian crossing, the polygon should be split on the 180 degree line. (https://tools.ietf.org/html/rfc7946#section-3.1.9) 
 
[example.zip](https://github.com/calvinmetcalf/shapefile-js/files/1048302/example.zip)

![shapefile](https://cloud.githubusercontent.com/assets/18443985/26735094/75278088-478e-11e7-887e-c4b32d15eda6.png)

![geojson](https://cloud.githubusercontent.com/assets/18443985/26735101/7a8e5dc6-478e-11e7-9a7c-b1727a806644.png)

**Comment by calvinmetcalf** [comment]
thanks, once Turfjs/turf#580 is merged I should be able to easily split both lines and polygons
