### ISSUE TITLE
Conflict with Prototype 1.6.0.3

### ISSUE THREAD

**Issue by robisaks** [calvinmetcalf/shapefile-js#82]
Kind of odd, but if the page has Prototype version 1.6.0.3, shp.js to load fails with "Uncaught WGS84"

> shp.js:14153 Uncaught WGS84
> Projection$1.callback @ shp.js:14153
> Projection$1 @ shp.js:14163
> Projection$1 @ shp.js:14149
> (anonymous) @ shp.js:14629
> (anonymous) @ shp.js:12805
> 54 @ shp.js:12808
> s @ shp.js:1
> (anonymous) @ shp.js:1
> (anonymous) @ shp.js:22268
> 58../binaryajax @ shp.js:22422
> s @ shp.js:1
> e @ shp.js:1
> (anonymous) @ shp.js:1
> (anonymous) @ shp.js:1
> (anonymous) @ shp.js:1

line where the failure is happening.
https://github.com/calvinmetcalf/shapefile-js/blob/gh-pages/dist/shp.js#L14153

Chrome Version 60.0.3112.90 (Official Build) (64-bit)

I'll be coding around it, but thought I'd post in case anyone else encounters this. I only tested 1.6.0.3, so it might not be an issue on newer versions.

**Comment by calvinmetcalf** [comment]
Does prototype per chance overwrite some of the array prototype methods?

**Comment by robisaks** [comment]
Yea, I'm sure it does. It overrides a lot of core js. It's pretty annoying to deal with.

**Comment by calvinmetcalf** [comment]
I think you may have answered your own question  ¯\_(ツ)_/¯

**Comment by robisaks** [comment]
Yup, I was just posting in case anyone else encountered it.
