### ISSUE TITLE
Importing shapefiles with projection is broken

### ISSUE THREAD

**Issue by senritsu** [calvinmetcalf/shapefile-js#85]
Since the [update of proj4](https://github.com/proj4js/proj4js/blob/master/lib/index.js#L11-L21) to use default exports this library doesn't work anymore when importing shape files in a zip with included projection file or a separate projection string.

The imports of `proj4` for this library would need to be changed to either use ES6 module imports, or to
`require('proj4').default`, otherwise what it imports isn't a function.

**Comment by estaub** [comment]
Maybe this is the fix for https://github.com/calvinmetcalf/shapefile-js/issues/75?

**Comment by senritsu** [comment]
@estaub seems very likely

**Comment by calvinmetcalf** [comment]
#84 should fix this I should be able to publish this latter today

**Comment by calvinmetcalf** [comment]
v3.4.1 is published

**Comment by estaub** [comment]
Confirmed as fix for #75.
