### ISSUE TITLE
issue importing zip

### ISSUE THREAD

**Issue by sigma-us** [calvinmetcalf/shapefile-js#87]
I am trying to use his package in an app I am building and I am unable to import shapefile zip to convert to GEOjson as the example shows, any insights would be greatly appreciated.

**Comment by calvinmetcalf** [comment]
what did you do exactly?

is there an error in the console?

is there an error in a promise somewhere?

there are an infinite ways to code something incorrectly so I'm going to need a _few_ more details

**Comment by calvinmetcalf** [comment]
what did you do exactly?

is there an error in the console?

is there an error in a promise somewhere?

there are an infinite ways to code something incorrectly so I'm going to need a few more details

**Comment by tipsychubbz** [comment]
This is the error i get 
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }

i did npm install shpjs --save and brought in shpjs to my service file and i am able to hit the api, im pointing to the right file and i get the above message. 

![screen shot 2017-09-29 at 10 39 04 am](https://user-images.githubusercontent.com/26858730/31028376-878174c4-a502-11e7-8b38-69f0fae53850.png)

**Comment by calvinmetcalf** [comment]
and http://localhost:80/testShp.zip has a file at it ?

**Comment by tipsychubbz** [comment]
yeah its in the root of my project as a test

**Comment by calvinmetcalf** [comment]
the error you are getting is that it can't access http://localhost:80/testShp.zip

**Comment by tipsychubbz** [comment]
alright so i changed the file path a couple of times and get the same result everytime, why would it be looking at localhost 80?

**Comment by calvinmetcalf** [comment]
maybe try loading with a fully qualified url with the http and what not
