### ISSUE TITLE
Z-values parsed incorrectly for some geometries.

### ISSUE THREAD

**Issue by jeff-tenhave** [calvinmetcalf/shapefile-js#89]
Z-values are parsed incorrectly for MultipointZ and PolylineZ/PolygonZ geometries with multiple paths or rings.

I think the problem with MultipointZ is in parseZMultiPoint:

```
var zOffset = 56 + (num << 4);
```
56 is the offset to the Z values in the record content, but _data_ does not include the first 4 bytes of the record content, so offset should be 52.

Similarily, in parseZPolyline:

```
var zOffset = 60 + (num << 4);
```

60 is the correct offset if there is only one path in the Polyline, but if there is more than one, it is incorrect.
It should be something like 56 + (num << 4) + (path_count << 2);

I would be happy to submit a fix for this.

**Comment by calvinmetcalf** [comment]
what would really be helpful is a test file

**Comment by calvinmetcalf** [comment]
but yeah your reasoning looks good so feel free to open a pull as well

**Comment by jeff-tenhave** [comment]
Here is a couple test files with a MultipointZ and a PolylineZ with multiple paths.

**Comment by calvinmetcalf** [comment]
thanks, added those to you pull and it looks great

**Comment by calvinmetcalf** [comment]
and published

**Comment by jeff-tenhave** [comment]
Great! Thanks for the quick turnaround.
