### ISSUE TITLE
parseShp returns an exception (data.readInt32 is not a function)

### ISSUE THREAD

**Issue by IgorGrechka** [calvinmetcalf/shapefile-js#98]
I'm trying to read shape file by using **shp.parseShp(shapeFileArray)** function but getting the exception:

![image](https://user-images.githubusercontent.com/1829604/41726409-be73a698-757a-11e8-81cf-6b72d662dee4.png)

![image](https://user-images.githubusercontent.com/1829604/41726664-4f49b216-757b-11e8-8be3-217100a7b03b.png)

![image](https://user-images.githubusercontent.com/1829604/41726784-94c035f4-757b-11e8-84a7-d8cd2081b497.png)

Shape file info from QGIS:

![image](https://user-images.githubusercontent.com/1829604/41726900-c8ba6bea-757b-11e8-90a1-2fb86a6bb912.png)

Can you tell me what the reason of this error? Thank you in advance!

**Comment by calvinmetcalf** [comment]
woops bug on my part, missed something in a conversion
